/**
 * Role-Plugin Service
 *
 * Converts .agent.toml profiles into Claude Code plugins, manages a local
 * marketplace at ~/agents/role-plugins/, and installs plugins into agent
 * working directories with --scope local.
 *
 * The local marketplace trick: Claude Code requires plugins to come from
 * registered marketplaces. We create a directory-based marketplace and
 * register it in settings.local.json via extraKnownMarketplaces. Each
 * agent then enables only its own role-plugin via a project-level
 * .claude/settings.local.json (equivalent to --scope local).
 *
 * IMPORTANT: This local marketplace mechanism is designed EXCLUSIVELY for
 * role-plugins generated by Haephestos or the AI Maestro API. It is NOT a
 * general-purpose plugin installation method. Regular plugins should always
 * be installed from GitHub-hosted marketplaces.
 */

import { parse as parseToml } from 'smol-toml'
import { join } from 'path'
import { homedir } from 'os'
import { mkdir, writeFile, readFile, readdir, rm, stat } from 'fs/promises'
import { existsSync } from 'fs'
import { execFile } from 'child_process'
import { promisify } from 'util'

const execFileAsync = promisify(execFile)

// ── Paths ──────────────────────────────────────────────────
const HOME = homedir()
const ROLE_PLUGINS_DIR = join(HOME, 'agents', 'role-plugins')
const MARKETPLACE_META_DIR = join(ROLE_PLUGINS_DIR, '.claude-plugin')
const MARKETPLACE_JSON = join(MARKETPLACE_META_DIR, 'marketplace.json')
const PLUGINS_DIR = join(ROLE_PLUGINS_DIR, 'plugins')
const CLAUDE_DIR = join(HOME, '.claude')
const SETTINGS_LOCAL = join(CLAUDE_DIR, 'settings.local.json')
const INSTALLED_FILE = join(CLAUDE_DIR, 'plugins', 'installed_plugins.json')

const MARKETPLACE_NAME = 'ai-maestro-local-roles-marketplace'

// ── Types ──────────────────────────────────────────────────

interface TomlAgent {
  name: string
  program?: string
  model?: string
  workingDirectory?: string
  description?: string
  teamId?: string
}

interface TomlSkills {
  primary?: string[]
  secondary?: string[]
  specialized?: string[]
}

interface TomlDependencies {
  plugins?: string[]
  skills?: string[]
  rules?: string[]
  agents?: string[]
  commands?: string[]
  hooks?: string[]
  mcp_servers?: string[]
  lsp_servers?: string[]
  output_styles?: string[]
  tools?: string[]
  frameworks?: string[]
}

interface TomlRules {
  items?: string[]
  recommended?: string[]
}

interface TomlRecommended {
  recommended?: string[]
}

interface ParsedToml {
  agent: TomlAgent
  skills?: TomlSkills
  dependencies?: TomlDependencies
  rules?: TomlRules
  agents?: TomlRecommended
  commands?: TomlRecommended
  hooks?: TomlRecommended
  mcp?: TomlRecommended
  lsp?: TomlRecommended
  output_styles?: TomlRecommended
  description?: { text?: string }
}

export interface RolePlugin {
  name: string
  version: string
  description: string
  model?: string
  program?: string
  pluginDir: string
}

// ── JSON helpers ───────────────────────────────────────────

async function loadJsonSafe(path: string): Promise<Record<string, unknown>> {
  if (!existsSync(path)) return {}
  try {
    const raw = await readFile(path, 'utf-8')
    return JSON.parse(raw)
  } catch {
    return {}
  }
}

async function saveJsonSafe(path: string, data: Record<string, unknown>): Promise<void> {
  const dir = join(path, '..')
  await mkdir(dir, { recursive: true })
  await writeFile(path, JSON.stringify(data, null, 2) + '\n', 'utf-8')
}

// ── TOML parsing ───────────────────────────────────────────

function parseAgentToml(tomlContent: string): ParsedToml {
  const parsed = parseToml(tomlContent) as Record<string, unknown>

  const agentSection = (parsed.agent || {}) as Record<string, unknown>
  if (!agentSection.name || typeof agentSection.name !== 'string') {
    throw new Error('TOML must have [agent] section with a name field')
  }

  return {
    agent: {
      name: agentSection.name as string,
      program: (agentSection.program as string) || 'claude-code',
      model: agentSection.model as string | undefined,
      workingDirectory: agentSection.workingDirectory as string | undefined,
      description: agentSection.description as string | undefined,
      teamId: agentSection.teamId as string | undefined,
    },
    skills: parsed.skills as TomlSkills | undefined,
    dependencies: parsed.dependencies as TomlDependencies | undefined,
    rules: parsed.rules as TomlRules | undefined,
    agents: parsed.agents as TomlRecommended | undefined,
    commands: parsed.commands as TomlRecommended | undefined,
    hooks: parsed.hooks as TomlRecommended | undefined,
    mcp: parsed.mcp as TomlRecommended | undefined,
    lsp: parsed.lsp as TomlRecommended | undefined,
    output_styles: parsed.output_styles as TomlRecommended | undefined,
    description: parsed.description as { text?: string } | undefined,
  }
}

// ── Plugin generation ──────────────────────────────────────

/**
 * Generate a Claude Code plugin from a .agent.toml profile.
 * Saves it to ~/agents/role-plugins/plugins/<name>/
 */
export async function generatePluginFromToml(
  tomlContent: string,
  agentDescription?: string,
): Promise<{ pluginName: string; pluginDir: string; mainAgentName: string }> {
  const config = parseAgentToml(tomlContent)
  const { agent } = config
  const pluginName = agent.name

  // Validate plugin name to prevent path traversal
  if (!/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/.test(pluginName)) {
    throw new Error(`Invalid agent name "${pluginName}": must be alphanumeric with hyphens/underscores, no path separators`)
  }

  const pluginDir = join(PLUGINS_DIR, pluginName)

  // Wipe existing plugin dir if it exists (regenerating)
  if (existsSync(pluginDir)) {
    await rm(pluginDir, { recursive: true })
  }

  // Create plugin directory structure
  const metaDir = join(pluginDir, '.claude-plugin')
  const agentsDir = join(pluginDir, 'agents')
  await mkdir(metaDir, { recursive: true })
  await mkdir(agentsDir, { recursive: true })

  // 1. plugin.json — prefer [description].text, fall back to [agent].description
  const pluginDescription = config.description?.text || agent.description || `Role plugin for ${pluginName}`
  const pluginJson = {
    name: pluginName,
    version: '1.0.0',
    description: pluginDescription,
  }
  await writeFile(join(metaDir, 'plugin.json'), JSON.stringify(pluginJson, null, 2) + '\n')

  // 2. agents/<plugin-name>-main-agent.md — the persona file
  // Follows the quad-match rule from the SKILL.md: agents/<plugin-name>-main-agent.md
  const mainAgentName = `${pluginName}-main-agent`
  const personaMd = buildPersonaMarkdown(mainAgentName, agent, config, agentDescription)
  await writeFile(join(agentsDir, `${mainAgentName}.md`), personaMd)

  // 3. Rules are NOT copied into the plugin.
  // Global rules (~/.claude/rules/) are auto-loaded by Claude Code for every session.
  // Project-level rules (.claude/rules/) are auto-loaded per project.
  // The [rules].recommended section in the TOML is metadata only (records which
  // rules the PSS profiler selected). No file copying needed — the plugin
  // installation with --scope local handles everything automatically.

  // 4. Save the original .agent.toml inside the plugin (quad-match: <plugin-name>.agent.toml)
  await writeFile(join(pluginDir, `${pluginName}.agent.toml`), tomlContent)

  // 5. Verify the plugin was created correctly by reading back the actual plugin.json
  // This guards against any discrepancy between what we intended and what exists on disk.
  const actualPluginJsonPath = join(metaDir, 'plugin.json')
  if (!existsSync(actualPluginJsonPath)) {
    throw new Error(`Plugin creation failed: ${actualPluginJsonPath} does not exist after writing`)
  }
  const actualPluginJson = JSON.parse(await readFile(actualPluginJsonPath, 'utf-8')) as Record<string, string>
  const actualName = actualPluginJson.name
  const actualDescription = actualPluginJson.description || ''
  const actualVersion = actualPluginJson.version || '1.0.0'

  // Verify quad-match: plugin.json name must equal directory name
  const dirName = pluginDir.split('/').pop()
  if (actualName !== dirName) {
    // Fix the mismatch — plugin.json name is the source of truth for the marketplace
    console.warn(`[role-plugin] Quad-match fix: plugin.json name "${actualName}" != dir name "${dirName}". Updating plugin.json.`)
    actualPluginJson.name = dirName!
    await writeFile(actualPluginJsonPath, JSON.stringify(actualPluginJson, null, 2) + '\n')
  }

  // Verify main-agent.md exists
  const mainAgentPath = join(agentsDir, `${mainAgentName}.md`)
  if (!existsSync(mainAgentPath)) {
    throw new Error(`Plugin creation failed: ${mainAgentPath} does not exist after writing`)
  }

  // 6. NOW register in marketplace — only after plugin is fully created and verified
  await ensureMarketplace()
  await updateMarketplaceManifest(
    actualPluginJson.name || pluginName,
    actualDescription,
    actualVersion,
  )

  return { pluginName, pluginDir, mainAgentName }
}

function buildPersonaMarkdown(
  mainAgentName: string,
  agent: TomlAgent,
  config: ParsedToml,
  agentDescription?: string,
): string {
  const { skills, dependencies } = config
  const lines: string[] = []

  const descText = config.description?.text || agent.description || `${agent.name} role agent`

  // Frontmatter — name must match the filename (quad-match rule)
  lines.push('---')
  lines.push(`name: ${mainAgentName}`)
  lines.push(`description: ${descText}`)
  if (agent.model) lines.push(`model: ${agent.model}`)
  lines.push('---')
  lines.push('')

  // Title and description
  lines.push(`# ${agent.name}`)
  lines.push('')
  if (agentDescription) {
    lines.push(agentDescription)
    lines.push('')
  } else if (config.description?.text) {
    lines.push(config.description.text)
    lines.push('')
  } else if (agent.description) {
    lines.push(agent.description)
    lines.push('')
  }

  // Skills section
  const allSkills = [
    ...(skills?.primary || []),
    ...(skills?.secondary || []),
    ...(skills?.specialized || []),
  ]
  if (allSkills.length > 0) {
    lines.push('## Skills')
    lines.push('')
    if (skills?.primary?.length) {
      lines.push('### Primary')
      skills.primary.forEach(s => lines.push(`- ${s}`))
      lines.push('')
    }
    if (skills?.secondary?.length) {
      lines.push('### Secondary')
      skills.secondary.forEach(s => lines.push(`- ${s}`))
      lines.push('')
    }
    if (skills?.specialized?.length) {
      lines.push('### Specialized')
      skills.specialized.forEach(s => lines.push(`- ${s}`))
      lines.push('')
    }
  }

  // Rules
  const rules = config.rules?.recommended || config.rules?.items || []
  if (rules.length > 0) {
    lines.push('## Rules')
    lines.push('')
    rules.forEach(r => lines.push(`- ${r}`))
    lines.push('')
  }

  // Sub-agents
  if (config.agents?.recommended?.length) {
    lines.push('## Agents')
    lines.push('')
    config.agents.recommended.forEach(a => lines.push(`- ${a}`))
    lines.push('')
  }

  // Commands
  if (config.commands?.recommended?.length) {
    lines.push('## Commands')
    lines.push('')
    config.commands.recommended.forEach(c => lines.push(`- /${c}`))
    lines.push('')
  }

  // Hooks
  if (config.hooks?.recommended?.length) {
    lines.push('## Hooks')
    lines.push('')
    config.hooks.recommended.forEach(h => lines.push(`- ${h}`))
    lines.push('')
  }

  // MCP Servers
  if (config.mcp?.recommended?.length) {
    lines.push('## MCP Servers')
    lines.push('')
    config.mcp.recommended.forEach(m => lines.push(`- ${m}`))
    lines.push('')
  }

  // LSP Servers
  if (config.lsp?.recommended?.length) {
    lines.push('## LSP Servers')
    lines.push('')
    config.lsp.recommended.forEach(l => lines.push(`- ${l}`))
    lines.push('')
  }

  // Output Styles
  if (config.output_styles?.recommended?.length) {
    lines.push('## Output Styles')
    lines.push('')
    config.output_styles.recommended.forEach(o => lines.push(`- ${o}`))
    lines.push('')
  }

  // Dependencies (user-scope prerequisites)
  if (dependencies) {
    lines.push('## Dependencies')
    lines.push('')
    const depEntries: [string, string[] | undefined][] = [
      ['Plugins', dependencies.plugins],
      ['Skills', dependencies.skills],
      ['Rules', dependencies.rules],
      ['Agents', dependencies.agents],
      ['Commands', dependencies.commands],
      ['Hooks', dependencies.hooks],
      ['MCP Servers', dependencies.mcp_servers],
      ['LSP Servers', dependencies.lsp_servers],
      ['Output Styles', dependencies.output_styles],
      ['Tools', dependencies.tools],
      ['Frameworks', dependencies.frameworks],
    ]
    for (const [label, items] of depEntries) {
      if (items?.length) {
        lines.push(`- **${label}:** ${items.join(', ')}`)
      }
    }
    lines.push('')
  }

  return lines.join('\n')
}

// ── Marketplace management ─────────────────────────────────

/**
 * Ensure the role-plugins marketplace directory and global registration exist.
 */
async function ensureMarketplace(): Promise<void> {
  // Create marketplace structure
  await mkdir(MARKETPLACE_META_DIR, { recursive: true })
  await mkdir(PLUGINS_DIR, { recursive: true })

  // Create marketplace.json if it doesn't exist
  if (!existsSync(MARKETPLACE_JSON)) {
    const manifest = {
      name: MARKETPLACE_NAME,
      version: '1.0.0',
      owner: { name: 'local' },
      metadata: {
        description: 'Local role-plugin marketplace managed by AI Maestro',
      },
      plugins: [],
    }
    await writeFile(MARKETPLACE_JSON, JSON.stringify(manifest, null, 2) + '\n')
  }

  // Register in global settings.local.json
  await registerMarketplaceGlobally()
}

async function registerMarketplaceGlobally(): Promise<void> {
  const settings = await loadJsonSafe(SETTINGS_LOCAL) as Record<string, Record<string, unknown>>
  const ekm = (settings.extraKnownMarketplaces || {}) as Record<string, unknown>

  // The canonical entry with the correct absolute path
  const canonicalEntry = {
    source: {
      source: 'directory',
      path: ROLE_PLUGINS_DIR,
    },
  }

  // Always ensure the canonical entry has the correct absolute path
  // (fixes corrupted or stale paths from earlier versions)
  const existing = ekm[MARKETPLACE_NAME] as Record<string, Record<string, string>> | undefined
  const existingPath = existing?.source?.path
  if (existingPath === ROLE_PLUGINS_DIR) return

  ekm[MARKETPLACE_NAME] = canonicalEntry
  settings.extraKnownMarketplaces = ekm
  await saveJsonSafe(SETTINGS_LOCAL, settings)
}

async function updateMarketplaceManifest(
  pluginName: string,
  description: string,
  version: string,
): Promise<void> {
  const manifest = await loadJsonSafe(MARKETPLACE_JSON) as Record<string, unknown>
  const plugins = (manifest.plugins || []) as Array<Record<string, string>>

  // Remove existing entry for this plugin (will re-add)
  const filtered = plugins.filter(p => p.name !== pluginName)
  filtered.push({
    name: pluginName,
    description,
    version,
    source: `./plugins/${pluginName}`,
  })
  manifest.plugins = filtered

  await writeFile(MARKETPLACE_JSON, JSON.stringify(manifest, null, 2) + '\n')
}

// ── Local installation ─────────────────────────────────────

/**
 * Install a role-plugin into an agent's working directory with local scope.
 * This creates <agentDir>/.claude/settings.local.json with the plugin enabled,
 * making it visible only to that agent's Claude Code session.
 *
 * @param pluginName - The plugin to install
 * @param agentDir - The agent's working directory (persona folder)
 * @param marketplaceName - Which marketplace the plugin comes from.
 *   Defaults to the local marketplace for Haephestos-generated plugins.
 *   For predefined role plugins, pass the official marketplace name.
 */
export async function installPluginLocally(
  pluginName: string,
  agentDir: string,
  marketplaceName: string = MARKETPLACE_NAME,
): Promise<void> {
  // Validate plugin name
  if (!/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/.test(pluginName)) {
    throw new Error(`Invalid plugin name "${pluginName}"`)
  }

  // Resolve ~ in agentDir
  const resolvedDir = agentDir.startsWith('~')
    ? agentDir.replace('~', HOME)
    : agentDir

  // Reject path traversal in agentDir
  if (resolvedDir.includes('..')) {
    throw new Error('agentDir must not contain ".."')
  }

  const pluginKey = `${pluginName}@${marketplaceName}`
  const claudeDir = join(resolvedDir, '.claude')
  const localSettings = join(claudeDir, 'settings.local.json')

  // Create .claude directory in agent's project
  await mkdir(claudeDir, { recursive: true })

  // Read or create settings.local.json
  const settings = await loadJsonSafe(localSettings) as Record<string, Record<string, unknown>>
  const ep = (settings.enabledPlugins || {}) as Record<string, boolean>
  ep[pluginKey] = true
  settings.enabledPlugins = ep
  await saveJsonSafe(localSettings, settings)

  // Track in global installed_plugins.json
  await mkdir(join(CLAUDE_DIR, 'plugins'), { recursive: true })
  const installed = await loadJsonSafe(INSTALLED_FILE) as Record<string, unknown>
  const pluginsMap = (installed.plugins || {}) as Record<string, unknown>
  const now = new Date().toISOString().replace('+00:00', 'Z')
  pluginsMap[pluginKey] = [{
    scope: 'local',
    version: '1.0.0',
    installedAt: now,
    lastUpdated: now,
    installPath: join(PLUGINS_DIR, pluginName),
    projectPath: resolvedDir,
  }]
  installed.plugins = pluginsMap
  await saveJsonSafe(INSTALLED_FILE, installed)
}

/**
 * Uninstall a role-plugin from an agent's working directory.
 */
export async function uninstallPluginLocally(
  pluginName: string,
  agentDir: string,
  marketplaceName: string = MARKETPLACE_NAME,
): Promise<void> {
  if (!/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/.test(pluginName)) {
    throw new Error(`Invalid plugin name "${pluginName}"`)
  }

  const resolvedDir = agentDir.startsWith('~')
    ? agentDir.replace('~', HOME)
    : agentDir

  if (resolvedDir.includes('..')) {
    throw new Error('agentDir must not contain ".."')
  }

  const pluginKey = `${pluginName}@${marketplaceName}`
  const localSettings = join(resolvedDir, '.claude', 'settings.local.json')

  if (existsSync(localSettings)) {
    const settings = await loadJsonSafe(localSettings) as Record<string, Record<string, unknown>>
    const ep = (settings.enabledPlugins || {}) as Record<string, boolean>
    delete ep[pluginKey]
    settings.enabledPlugins = ep
    await saveJsonSafe(localSettings, settings)
  }

  // Remove from installed_plugins.json
  if (existsSync(INSTALLED_FILE)) {
    const installed = await loadJsonSafe(INSTALLED_FILE) as Record<string, unknown>
    const pluginsMap = (installed.plugins || {}) as Record<string, unknown>
    delete pluginsMap[pluginKey]
    installed.plugins = pluginsMap
    await saveJsonSafe(INSTALLED_FILE, installed)
  }
}

// ── Listing ────────────────────────────────────────────────

/**
 * List all available role plugins in the marketplace.
 */
export async function listRolePlugins(): Promise<RolePlugin[]> {
  if (!existsSync(PLUGINS_DIR)) return []

  const entries = await readdir(PLUGINS_DIR)
  const plugins: RolePlugin[] = []

  for (const entry of entries) {
    const pluginDir = join(PLUGINS_DIR, entry)
    const pluginJsonPath = join(pluginDir, '.claude-plugin', 'plugin.json')
    const tomlPath = join(pluginDir, `${entry}.agent.toml`)

    const entryStat = await stat(pluginDir).catch(() => null)
    if (!entryStat?.isDirectory()) continue
    if (!existsSync(pluginJsonPath)) continue

    try {
      const meta = JSON.parse(await readFile(pluginJsonPath, 'utf-8'))
      let model: string | undefined
      let program: string | undefined

      // Try to extract model/program from the saved TOML
      if (existsSync(tomlPath)) {
        try {
          const tomlContent = await readFile(tomlPath, 'utf-8')
          const parsed = parseAgentToml(tomlContent)
          model = parsed.agent.model
          program = parsed.agent.program
        } catch { /* ignore parse errors */ }
      }

      plugins.push({
        name: meta.name || entry,
        version: meta.version || '1.0.0',
        description: meta.description || '',
        model,
        program,
        pluginDir,
      })
    } catch { /* skip malformed plugins */ }
  }

  return plugins
}

/**
 * Delete a role plugin from the marketplace.
 */
export async function deleteRolePlugin(pluginName: string): Promise<void> {
  if (!/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/.test(pluginName)) {
    throw new Error(`Invalid plugin name "${pluginName}"`)
  }

  const pluginDir = join(PLUGINS_DIR, pluginName)
  if (existsSync(pluginDir)) {
    await rm(pluginDir, { recursive: true })
  }

  // Remove from marketplace manifest
  if (existsSync(MARKETPLACE_JSON)) {
    const manifest = await loadJsonSafe(MARKETPLACE_JSON) as Record<string, unknown>
    const plugins = (manifest.plugins || []) as Array<Record<string, string>>
    manifest.plugins = plugins.filter(p => p.name !== pluginName)
    await writeFile(MARKETPLACE_JSON, JSON.stringify(manifest, null, 2) + '\n')
  }

  // Remove from global enabledPlugins
  const pluginKey = `${pluginName}@${MARKETPLACE_NAME}`
  if (existsSync(SETTINGS_LOCAL)) {
    const settings = await loadJsonSafe(SETTINGS_LOCAL) as Record<string, Record<string, unknown>>
    const ep = (settings.enabledPlugins || {}) as Record<string, boolean>
    delete ep[pluginKey]
    settings.enabledPlugins = ep
    await saveJsonSafe(SETTINGS_LOCAL, settings)
  }
}

// ── Unified persona creation ─────────────────────────────

/**
 * The 6 predefined AI Maestro role plugins.
 * Downloaded from their GitHub repos into the local marketplace
 * at ~/agents/role-plugins/plugins/ via syncDefaultRolePlugins().
 */
export const PREDEFINED_ROLE_PLUGINS: Record<string, { marketplace: string; mainAgent: string }> = {
  'ai-maestro-assistant-manager-agent': { marketplace: MARKETPLACE_NAME, mainAgent: 'amama-assistant-manager-main-agent' },
  'ai-maestro-chief-of-staff':         { marketplace: MARKETPLACE_NAME, mainAgent: 'ai-maestro-chief-of-staff-main-agent' },
  'ai-maestro-architect-agent':        { marketplace: MARKETPLACE_NAME, mainAgent: 'ai-maestro-architect-agent-main-agent' },
  'ai-maestro-integrator-agent':       { marketplace: MARKETPLACE_NAME, mainAgent: 'ai-maestro-integrator-agent-main-agent' },
  'ai-maestro-orchestrator-agent':     { marketplace: MARKETPLACE_NAME, mainAgent: 'ai-maestro-orchestrator-agent-main-agent' },
  'ai-maestro-programmer-agent':       { marketplace: MARKETPLACE_NAME, mainAgent: 'ai-maestro-programmer-agent-main-agent' },
}

/**
 * GitHub repos for the 6 default role plugins.
 * syncDefaultRolePlugins() clones these into ~/agents/role-plugins/plugins/
 */
const DEFAULT_ROLE_PLUGIN_REPOS: Record<string, { repo: string; description: string }> = {
  'ai-maestro-assistant-manager-agent': { repo: 'Emasoft/ai-maestro-assistant-manager-agent', description: 'Assistant Manager role plugin' },
  'ai-maestro-chief-of-staff':         { repo: 'Emasoft/ai-maestro-chief-of-staff',          description: 'Chief of Staff role plugin' },
  'ai-maestro-architect-agent':        { repo: 'Emasoft/ai-maestro-architect-agent',         description: 'Architect role plugin' },
  'ai-maestro-integrator-agent':       { repo: 'Emasoft/ai-maestro-integrator-agent',        description: 'Integrator role plugin' },
  'ai-maestro-orchestrator-agent':     { repo: 'Emasoft/ai-maestro-orchestrator-agent',      description: 'Orchestrator role plugin' },
  'ai-maestro-programmer-agent':       { repo: 'Emasoft/ai-maestro-programmer-agent',        description: 'Programmer role plugin' },
}

// ── Default role plugin sync ──────────────────────────────

export interface SyncDefaultsResult {
  synced: string[]
  skipped: string[]
  errors: Array<{ name: string; error: string }>
}

/**
 * Download the 6 default role plugins from GitHub into the local marketplace.
 * Skips plugins that already exist (have a valid plugin.json).
 * Uses `git clone --depth 1` for minimal bandwidth, then removes .git/.
 *
 * @param force - If true, re-downloads even if the plugin already exists
 */
export async function syncDefaultRolePlugins(force = false): Promise<SyncDefaultsResult> {
  await ensureMarketplace()

  const synced: string[] = []
  const skipped: string[] = []
  const errors: Array<{ name: string; error: string }> = []

  for (const [pluginName, { repo, description }] of Object.entries(DEFAULT_ROLE_PLUGIN_REPOS)) {
    const pluginDir = join(PLUGINS_DIR, pluginName)
    const pluginJsonPath = join(pluginDir, '.claude-plugin', 'plugin.json')

    // Skip if already exists and has plugin.json (unless force)
    if (!force && existsSync(pluginJsonPath)) {
      skipped.push(pluginName)
      // Ensure it's registered in the manifest even if skipped
      try {
        const meta = JSON.parse(await readFile(pluginJsonPath, 'utf-8'))
        await updateMarketplaceManifest(pluginName, meta.description || description, meta.version || '1.0.0')
      } catch { /* ignore */ }
      continue
    }

    try {
      // Clean target dir if it exists but is incomplete
      if (existsSync(pluginDir)) {
        await rm(pluginDir, { recursive: true })
      }

      // Clone the repo with depth 1 (minimal download)
      await execFileAsync('git', [
        'clone', '--depth', '1',
        `https://github.com/${repo}.git`,
        pluginDir,
      ], { timeout: 120000 })

      // Remove .git directory — not needed in the marketplace
      const gitDir = join(pluginDir, '.git')
      if (existsSync(gitDir)) {
        await rm(gitDir, { recursive: true })
      }

      // Read plugin.json to get actual description/version
      if (existsSync(pluginJsonPath)) {
        const meta = JSON.parse(await readFile(pluginJsonPath, 'utf-8'))
        await updateMarketplaceManifest(
          pluginName,
          meta.description || description,
          meta.version || '1.0.0',
        )
      } else {
        await updateMarketplaceManifest(pluginName, description, '1.0.0')
      }

      synced.push(pluginName)
      console.log(`[role-plugins] Synced default: ${pluginName}`)
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      errors.push({ name: pluginName, error: msg })
      console.error(`[role-plugins] Failed to sync ${pluginName}:`, msg)
    }
  }

  return { synced, skipped, errors }
}

export interface CreatePersonaResult {
  personaName: string
  agentDir: string
  pluginName: string
  mainAgentName: string
  marketplaceName: string
}

/**
 * Unified persona creation — used by both the wizard (predefined role plugins)
 * and Haephestos (custom TOML-generated plugins).
 *
 * Exactly one of `tomlContent` or `pluginName` must be provided:
 * - tomlContent: Haephestos flow — generates a new plugin, adds to local marketplace
 * - pluginName: Wizard flow — uses an existing predefined role plugin
 *
 * In both cases, creates ~/agents/<personaName>/ and installs the plugin
 * with --scope local into that folder.
 */
export async function createPersona(opts: {
  personaName: string
  tomlContent?: string
  pluginName?: string
  marketplaceName?: string
  agentDescription?: string
}): Promise<CreatePersonaResult> {
  const { personaName, tomlContent, agentDescription } = opts

  // Validate persona name: lowercase alphanumeric + hyphens
  if (!/^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/.test(personaName)) {
    throw new Error('personaName must be lowercase alphanumeric with hyphens (e.g. "peter-bot")')
  }

  // Must provide exactly one source
  if (tomlContent && opts.pluginName) {
    throw new Error('Provide either tomlContent or pluginName, not both')
  }
  if (!tomlContent && !opts.pluginName) {
    throw new Error('Either tomlContent or pluginName is required')
  }

  let pluginName: string
  let mainAgentName: string
  let marketplaceName: string

  if (tomlContent) {
    // Haephestos flow: generate plugin from TOML → local marketplace
    const result = await generatePluginFromToml(tomlContent, agentDescription)
    pluginName = result.pluginName
    mainAgentName = result.mainAgentName
    marketplaceName = MARKETPLACE_NAME
  } else {
    // Wizard flow: use existing predefined plugin
    pluginName = opts.pluginName!
    const predefined = PREDEFINED_ROLE_PLUGINS[pluginName]
    if (predefined) {
      marketplaceName = opts.marketplaceName || predefined.marketplace
      mainAgentName = predefined.mainAgent
    } else {
      // Custom plugin name — caller must specify marketplace
      marketplaceName = opts.marketplaceName || MARKETPLACE_NAME
      mainAgentName = `${pluginName}-main-agent`
    }
  }

  // Create the persona folder: ~/agents/<personaName>/
  const agentDir = join(HOME, 'agents', personaName)
  await mkdir(agentDir, { recursive: true })

  // Install the plugin locally into the persona folder
  await installPluginLocally(pluginName, agentDir, marketplaceName)

  return {
    personaName,
    agentDir,
    pluginName,
    mainAgentName,
    marketplaceName,
  }
}
